### ISSUE TITLE
missing _CoreScanner_i.c file

### ISSUE THREAD

**Issue by KuehBK** [zebra-technologies/Scanner-SDK-for-Windows#1]
Downloaded v3.6.1.0. Tried to compile the SampleApp_CPP.prj with the source code, encountered missing _CoreScanner_i.c file.
What did I do wrongly? 
How do I resolve it

**Comment by yeo32cjf** [comment]
I experienced same thing and I posted same post in zebra developer portal.
But I finally solved it, making nonofficial file.

I explored "_CoreScanner.h" file, and I found out that the problem is some variables declared as EXTERN_C.
These 4 variables are declared as EXTERN_C.
- IID_ICoreScanner
- LIBID_CoreScanner
- DIID__ICoreScannerEvents
- CLSID_CCoreScanner

These variables need to have proper initial value.(GUID of class or library)
I found out classes' GUID from "_CoreScanner.h" and library ID from c# project

So this Nonofficial _CoreScanner_i.c code works!

========_CoreScanner_i.c=========(Nonofficial)
#include "rpc.h"
#include "rpcndr.h"

const IID IID_ICoreScanner = { 0x2105896C, 0x2B38, 0x4031, {0xBD,0x0B,0x7A,0x9C,0x4A,0x39,0xFB,0x93} };
const IID LIBID_CoreScanner = { 0xDB07B9FC, 0x18B0, 0x4B55, {0x9A,0x44,0x31,0xD2,0xC2,0xF8,0x78,0x75} };
const IID DIID__ICoreScannerEvents = { 0x981E3D8B, 0xC756, 0x4195, {0xA7,0x02,0xF1,0x98,0x96,0x50,0x31,0xC6} };
const CLSID CLSID_CCoreScanner = { 0x9F8D4F16, 0x0F61, 0x4A38, {0x98,0xB3,0x1F,0x6F,0x80,0xF1,0x1C,0x87} };

**Comment by zebradcs** [comment]
Relevant _CoreScanner_i.c file added into the source. Please pull it from the commit ID a53b92563d7ef7998c17bb7cdb027748a8b604b1
